steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    args:
      - '-c'
      - >-
        echo "$BRANCH_NAME DEPLOYING";
        gsutil -m cp -r ./dags/url_content_topics/ gs://us-central1-sandbox-de-72ce2372-bucket/dags/;
        gsutil -m cp -r ./src/* gs://us-central1-sandbox-de-72ce2372-bucket/data/url_content_topics/src/;
        gsutil -m cp -r ./utils/* gs://us-central1-sandbox-de-72ce2372-bucket/data/url_content_topics/utils/;
        gsutil -m cp -r ./config/* gs://us-central1-sandbox-de-72ce2372-bucket/data/url_content_topics/config/;
    id: Deploy
    entrypoint: bash
options:
  logging: CLOUD_LOGGING_ONLY